### PR TITLE
Add checking for color in data to avoid exceptions

### PR DESCRIPTION
**Pull request by airens**
For some devices Tuya servers can reply no "color" section in response data for "colour" mode which lead to exceptions in "brightness" function. 
Example data:
```json
{
"payload": {"data": {"brightness": "255",
    "color_mode": "colour",
    "online": true,
    "state": "true"}},
  "header": {"code": "SUCCESS", "payloadVersion": 1}
}
````

### CODE REVIEW

**Comment by PaulAnnekov** [comment]
Nice job! ;)

**Comment by majorsl** [comment]
I tried this change in my HA and, while it does restore functionality to my lights, any of my bulbs with cards have lost the color wheel and have the brightness slider only now.

Setting the color in automations will still work it seems, but you lose the ability to do it "manually" and on the fly for bulbs/groups of bulbs.

**Comment by airens** [comment]
> I tried this change in my HA and, while it does restore functionality to my lights, any of my bulbs with cards have lost the color wheel and have the brightness slider only now.
> 
> Setting the color in automations will still work it seems, but you lose the ability to do it "manually" and on the fly for bulbs/groups of bulbs.

Yeah, I actually had to change Tuya component a little bit to make such lights work. Try to change
```python
supports = SUPPORT_BRIGHTNESS
```
in `light.py` to 
```python
supports = SUPPORT_BRIGHTNESS | SUPPORT_COLOR
```
Keep in mind that It'll forcelly allow Home assistant to control color for `ALL` Tiya lights

P.S> It's just workaround, unfortunately, and it's can't be implemented in official component

**Comment by majorsl** [comment]
Thanks, that's what I'll probably do since all my lights are color capable. Does a custom_component override a built in component of the same name? I've done customs, but none that duplicate existing official ones.

Strange they changed it yet other services like Alexa still understand the differences. Makes me wonder if the API for the color attribute got moved/renamed and not removed.

Thanks for your work on this!

**Comment by airens** [comment]
> Thanks, that's what I'll probably do since all my lights are color capable. Does a custom_component override a built in component of the same name? I've done customs, but none that duplicate existing official ones.
> 
> Strange they changed it yet other services like Alexa still understand the differences. Makes me wonder if the API for the color attribute got moved/renamed and not removed.
> 
> Thanks for your work on this!

As far as I know, custom_components has higher priority. Just try

**Pull request merged**
