### PR TITLE
Manage digits in target temperature for Climate Devices

### PR DESCRIPTION
**Pull request by ollo69**
This PR contain 2 fixes for climate device:

1. add list of allowed temperature steps to use in HA and fix the `set_temperature` method to manage digits: this will allow in HA to define different temperature steps and will manage steps with decimals. This PR replace PR #54 and PR #59  

2. add a parameter to `set_temperature` method to choose update mode (fix for issue #51) 

I will create required PR in HA to bump new version and apply required changes if this PR will be approved.

### CODE REVIEW

**Review by matitalatina — APPROVED** [review]
I tested this code and it works with my thermostat BHT-002-GCLW

**Comment by matitalatina** [comment]
@PaulAnnekov please, can you have a look at it? We can't proceed further otherwise.

**Comment by PaulAnnekov** [comment]
@matitalatina @ollo69 thank you. Already in version 0.0.10.

**Comment by ollo69** [comment]
Thanks @PaulAnnekov, I will create HA PR this w.e.

**Pull request merged**
