### PR TITLE
Add support for decimal values on set temperature

### PR DESCRIPTION
**Pull request by matitalatina**
This PR is needed for this: https://github.com/home-assistant/core/pull/43970
I added the ability to set a temperature with decimals.

### CODE REVIEW

**Comment by 3v1n0** [comment]
I handled this in #54 a bit differently as if the device has no support for decimal values at all, maybe we don't want to accept non-integer ones, no?

**Comment by PaulAnnekov** [comment]
Please, try to come to a consensus on what PR to approve.

**Comment by matitalatina** [comment]
We're trying to fix the same issue but differently.
Mine is a more "agnostic" approach. I'm just adding decimal values because some thermostats handle it. I tried with mine and it works, even if I put some decimal value that it doesn't support (e.g 17.7 C), it doesn't get any error, he set the rounded value on the thermostat (17.5).
@3v1n0 tries to do the same but he tries to understand if the device supports halves or not. I don't understand some of his logic, I added some comments on his PR.
We will agree ASAP.

**Comment by matitalatina** [comment]
We're putting our effort here https://github.com/PaulAnnekov/tuyaha/pull/61
I'm closing this one,

**Pull request closed without merging**
